### ISSUE TITLE
Visualization Rmd Part 2: 2nd figure not rendering

### ISSUE THREAD

**Issue by marknovak** [analyticalworkflows/TeachingMaterials#11]
There's a bug in the `segments()` code of the second figure that keeps the figure from being rendered.

**Comment by marknovak** [comment]
This code (written by Ben) wasn't used this year, but in case it is needed in future years...
(I can't figure out what's causing the problem.)

**Comment by BenjaminDalziel** [comment]
Fixed and added some content.
