### ISSUE TITLE
Scrap GitHub Issue-based feedback on project presentations

### ISSUE THREAD

**Issue by marknovak** [analyticalworkflows/TeachingMaterials#17]
Scrap GitHub Issue-based feedback on project presentations (remove from READMEs)

**Comment by BenjaminDalziel** [comment]
I think we did this last year. I don't remember it as terrible. What was the issue and what would you like to do instead for student feedback on presentations @marknovak?

**Comment by marknovak** [comment]
The feedback was pretty empty and i think it would be better to do something like give the accountabilibuddies time to provide real feedback to each other.

**Comment by BenjaminDalziel** [comment]
Yes, I do recall thinking student comments were often pretty empty. How about we plan to open the floor briefly after each presentation for verbal feedback from the group + give accountabilibuddies time as you suggest?

**Comment by marknovak** [comment]
For how long?  I recall being pretty crunched for time.  Perhaps having a single longer period at the end of the class period instead?  (I suspect that group discussion will remain pretty empty, so suggest only asking the group briefly for input and then switching over to pairwise talk.)

**Comment by BenjaminDalziel** [comment]
Like a strict 30-60 seconds. Enough for 1-2 comments, if the other students have important ones to share. That did happen sometimes last time.

**Comment by marknovak** [comment]
Is that really worth it?  That's equivalent to the time it takes to get the next speaker ready.

**Comment by BenjaminDalziel** [comment]
I think it could be. You never know when someone is going to have an important comment and it might not be the ab buddy. If no one has a comment we skip it?

**Comment by BenjaminDalziel** [comment]
I updated the 3 readmes for the presentation classes.
