### ISSUE TITLE
Typo - Intro2Git

### ISSUE THREAD

**Issue by rcterry** [analyticalworkflows/TeachingMaterials#20]
Second to last sentence in Git paragraph (on page 2) should end with features, not feature.

**Comment by rcterry** [comment]
Page 4, Paragraph 4: browser is not spelled browswer :-)

**Comment by marknovak** [comment]
thanks!

**Comment by marknovak** [comment]
Fixed by 7d4f80a65d723b3fe80e510a4c4066d12ae6c6d0
