### ISSUE TITLE
Broken link:  TeachingMaterials/classes/StructuredProjects/README.md 

### ISSUE THREAD

**Issue by sielerjm** [analyticalworkflows/TeachingMaterials#22]
Found here: https://github.com/analyticalworkflows/TeachingMaterials/blob/288673ef32348133ecedb35c934f45c46aff411d/classes/StructuredProjects/README.md#L19

Broken link: Broken link: https://github.com/analyticalworkflows/TeachingMaterials/blob/master/classes/StructuredProjects/classes/Implementation

**Comment by marknovak** [comment]
Fixed by https://github.com/analyticalworkflows/TeachingMaterials/commit/d9781fc
