### ISSUE TITLE
Fall 2022 setup

### ISSUE THREAD

**Issue by BenjaminDalziel** [analyticalworkflows/TeachingMaterials#25]
Setup checklist for course instructors - Fall 2022

- [x] Update schedule in TeachingMaterials/README.md, including noting Ben/Mark availability
- [x] Update syllabus
- [x] Revise other sections of TeachingMaterials/README.md as needed
- [x] Create class of 2022 Team in the analyticalworkflows organization
- [x] #26
- [x] Write to Cosine (or whoever they merged into) and give them each student's ONID to have access enabled to the Cosine HPC.

**Comment by marknovak** [comment]
You may want to consider sending out an email to all students, telling them they'll need to have a project to work on (and hence oughta likely talk to their advisors now, if they don't have something of their own yet).

**Comment by marknovak** [comment]
Note #16, #17, and, for course content, #8.

**Comment by marknovak** [comment]
And #15 too

**Comment by BenjaminDalziel** [comment]
There are two distinction copes of the syllabus and I edited the wrong one. Fixing now and reducing to one official copy.
