### ISSUE TITLE
Send email to all F2022 students

### ISSUE THREAD

**Issue by BenjaminDalziel** [analyticalworkflows/TeachingMaterials#26]
Things to mention in the email:

-telling them they need to have a project to work on and may want to speak to their advisors now if they don't have something of their own yet

-bring a laptop or let us know if you don't have access

-any other prework we typically do: e.g..software installed

**Comment by BenjaminDalziel** [comment]
Email draft [here](https://github.com/analyticalworkflows/TeachingMaterials/blob/master/admin/README.md) under week 0 email. Could you please take a look @marknovak?

**Comment by marknovak** [comment]
Looks great.  Send away!
