### ISSUE TITLE
Move 'framing-discussion.md' into 'Structured Projects.tex' notes?

### ISSUE THREAD

**Issue by marknovak** [analyticalworkflows/TeachingMaterials#30]
@BenjaminDalziel, I see that you wrote some introductory [framing-discussion.md](classes/StructuredProjects/tex/framing-discussion.md) for the "Structured Projects" lecture.  Is there a reason you didn't want to include this in the introduction at the top of the [tex](classes/StructuredProjects/tex/StructuredProjects.tex) file that we have the students read as preparation?

**Comment by marknovak** [comment]
That is to say, I like what you wrote and don't see why it couldn't be intergrated into the tex readings.

**Comment by BenjaminDalziel** [comment]
Will do

**Comment by marknovak** [comment]
I'm working on that lecture right now, so I'll go ahead and do it.

**Comment by marknovak** [comment]
Addressed by https://github.com/analyticalworkflows/TeachingMaterials/commit/4dcf42879ebe868e60907c2d11cde6115bee5259
