### ISSUE TITLE
Update 'Intro2Git' notes and tex

### ISSUE THREAD

**Issue by marknovak** [analyticalworkflows/TeachingMaterials#35]
...in light of Git and GitHub having already been installed (and introduced) during 'Welcome'.

**Comment by marknovak** [comment]
We now have them installing [GitHub Desktop](https://desktop.github.com) on day 1 of the course.  (This change still needs to be reflected in the 'Welcome' lecture.)  This is certainly an easier set-up than what we did in the past (which required us to ellaborate more during the `Intro2Git` lecture):  it means they don't have to install Git separately.  But it does have consequences which we should probably learn more about and discuss in class.  The clearest of these is that GitHub Desktop installs only a "light" version of Git.  There is thus, for example, no command-line access to Git.

**Comment by BenjaminDalziel** [comment]
Agreed regarding some ripple effects to be discussed. I guess we could consider having them install the "non-lite" version of Git in the Git lecture. But maybe the first question to answer is this: do we want to cover *anything* about working with Git at the command-line in this class? What fraction of students would ever want or benefit from learning something about this? Alternatively, they get familiar with Git using GUIs, and can go learn command-line later if they want. Isn't just using Git/Github the "win" we are looking for?

**Comment by marknovak** [comment]
Agreed, those are all good things to think about (and ask the students themselves)

**Comment by marknovak** [comment]
A question i have is what happens when GitHub Desktop is uninstalled?  Will all hidden git files it has produced work just as well when Git is subsequently installed?

**Comment by marknovak** [comment]
I think our concensus from last class is that we should give students enough knowledge to make their own decision.  That means we should discuss the pros and cons of GitHub Desktop vs. full Git in the Intro2Git Part 1 class.  I do not think that doing that on Day 1 of the course is a good idea.  That alsomeans that we should _not_ having students install GitHub Desktop on Day 1.

Thoughts?

**Comment by BenjaminDalziel** [comment]
I agree about letting students make their own informed decision. I also agree that we can't discuss pros and cons of a full Git install on day 1.

However, I don't agree that students therefore shouldn't install Github desktop on day 1. Doing the install on Day 1 allows them to start working with version control and Github right away, which helps understanding the underlying concepts when we present them. Also, to make an informed decision I think they should at least try Github desktop before deciding. 

The only reason that I can see not to have them start with Github desktop is if it has some lasting consequence for working with Git / Rstudio later. I'm still skeptical of that. What evidence do we currently have?

**Comment by marknovak** [comment]
> Doing the install on Day 1 allows them to start working with version control and Github right away,

Yes, but it also means they're more likely to set up their project poorly, and/or load everything they have onto the repo, and/or thus need to redo everything once they do learn the better way to do things.

**Comment by BenjaminDalziel** [comment]
The activity on day 1 is just to make a repo with a README file and do one commit / push. It is not to setup their projects, and we can warn them not to load a bunch of stuff. I say they can use a dummy repo. Having a repo also gives them a place to experiment with folder structure, a place to store their workflow diagrams, and their project proposals. All of that happens before the first Git lecture.

**Comment by marknovak** [comment]
That's why we used to have Git Part 1 as the second class (#37), followed immediately by Project Structure and only then the rest (Workflow diagrams, etc.).  They don't _need_ to start working on their own projects from day 1 or even week 1.   In fact, I don't think we want them to (given, among other things, that many are likely to do things that end up causing confusion)!  Indeed, many are still figuring out what project they want to focus on and need discussion thereof before anything else can happen.
